### ISSUE TITLE
[severus] Linux Mint 21.1 JavaScript Error using AMD64 *.deb (Version 1.3.1/2 Only)

### ISSUE THREAD

**Issue by cas206** [owlbear-rodeo/kenku-fm#82] opened 2023-03-23 17:44 UTC
**Describe the bug**
Starting as kenku-fm from the command line gives an error.  The process hangs until killed.

A JavaScript error occurred in the main process
Uncaught Exception:
Error: libssl.so.1.1: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1810)
    at Module._extensions..node (node:internal/modules/cjs/loader:1205:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1810)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13339)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at 85109 (/usr/lib/kenku-fm/resources/app/.webpack/main/index.js:2:58)
    at __webpack_require__ (/usr/lib/kenku-fm/resources/app/.webpack/main/index.js:14:517194)

**To Reproduce**
1) Install  kenku-fm_1.3.2_amd64.deb with dpkg.
2) Run kenku-fm at command line.
 
**Expected behavior**
Normal Kenku-FM behavior

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: 
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=21.1
DISTRIB_CODENAME=vera
DISTRIB_DESCRIPTION="Linux Mint 21.1 Vera"

**Additional context**
I was running version 1.2.2 with no errors (except sound quit since I last used it a week ago).
I tested an install and run of prior versions, 1.2.4, and 1.3.0.  These install and run without error.
It's just version 1.3.2 that gives the JavaScript startup error.

**Comment by lanice** [comment] 2023-03-23 22:44
I've had the same issue (Ubuntu 22.04). Tried 1.3.2, wouldn't start. Installed 1.3.1, same issue. Installed 1.3.0, it works. So I'm on 1.3.0 at the moment.

**Comment by cas206** [comment] 2023-03-23 23:49
For some reason my eyes glazed over and missed seeing the 1.3.1 Release.  I tried it, also, and as the prior commenter noted, it also had the same error.

**Comment by nthouliss** [comment] 2023-03-24 00:21
1.3.1 onwards changed how we evaluate certificates because of an issue with Windows (#77). 

In terms of functionality, you're not missing anything between 1.3.0 and 1.3.2, so stick with it for now. We'll see what we need to do to patch it out without affecting Windows as well. It may take us some time. Good thing is we can reproduce this on our end.

**Comment by Lim-Dul** [comment] 2023-03-24 20:02
OK, so, the problem is that Ubuntu and its downstream distros like Mint removed OpenSSL 1.1.1 support starting with 22.04 and use OpenSSL 3 now. The issue is that the rust-openssl bindings don't detect the OpenSSL version on Ubuntu et al correctly. There's a ton of talk about it on the https://github.com/sfackler/rust-openssl/issues?q=is%3Aissue+is%3Aopen+openssl GitHub.

Anyways, until this is resolved, all I can offer is a work-around, with which I managed to run KenkuFM on Ubuntu 22.04 LTS. Adapted from an answer here:
https://stackoverflow.com/questions/72133316/libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-directory

Use the following commands in order:
```bash
sudo apt install build-essential
wget https://www.openssl.org/source/openssl-1.1.1t.tar.gz
tar -zxvf openssl-1.1.1t.tar.gz
cd openssl-1.1.1t
./config && make && make test
mkdir -p $HOME/opt/lib
mv libcrypto.so.1.1 $HOME/opt/lib/
mv libssl.so.1.1 $HOME/opt/lib/

export LD_LIBRARY_PATH=$HOME/opt/lib:$LD_LIBRARY_PATH >> $HOME/.bashrc
```

**Comment by nthouliss** [comment] 2023-03-27 06:24
We've published a release candidate package, it was running successfully without needed to get OpenSSL 1.1 installed on our test but it'd still be nice to have it double-checked by ya'll. 

https://github.com/owlbear-rodeo/kenku-fm/releases/tag/v1.3.3-rc

**Comment by lanice** [comment] 2023-03-27 08:31
Just tested it, works for me!

**Comment by Lim-Dul** [comment] 2023-03-27 09:44
Confirmed fixed on 1.3.3-rc on Ubuntu 22.04 and Fedora 36 without OpenSSL 1.1.
See `lsb_release -a` for both systems and no `libssl.so.1.1` via `find` on screenshots. Not testing Mint since it is a descendant of Ubuntu anyways.
![image](https://user-images.githubusercontent.com/428324/227905291-5807277e-11d6-4952-88ac-5f79f840ad57.png) 
![image](https://user-images.githubusercontent.com/428324/227905327-89559af3-7c00-4615-9a14-d2b767699378.png)

**Comment by nthouliss** [comment] 2023-03-29 01:46
This should no longer be an issue for v1.4.0 (which reverts changes between v1.3.0 and v1.3.2)

I'm going to leave this open as we'll be tracking it as part of our experimental version

**Comment by lanice** [comment] 2023-03-29 07:55
Just out of curiosity, v1.3.0 introduced the new Rust audio pipeline, which is also being reverted in v1.4.0? Are there too many issue with that, or why is that being removed?

**Comment by Lim-Dul** [comment] 2023-03-29 08:06
> Just out of curiosity, v1.3.0 introduced the new Rust audio pipeline, which is also being reverted in v1.4.0? Are there too many issue with that, or why is that being removed?

Unfortunately yes. As is often the case with major changes, it works perfectly fine for some users in certain setups but there seems to be not insignificant number of people for whom KenkuFM completely broke... :(

See this announcement on Discord:
https://discord.com/channels/795808973743194152/892066860575637584/1090459114833985577

As well as Issues: #85 #88 in addition to this one.

**Comment by lanice** [comment] 2023-03-29 08:12
Got it, yes that makes sense. Glad to read that there will be an experimental version continuing the new pipeline!

**Comment by nthouliss** [comment] 2023-03-31 02:40
This should be fixed as part of our experimental release, you can find it in our releases page or at https://www.kenku.fm/experimental

**Closed by nthouliss** 2023-03-31 02:40 UTC
Labels: bug, severus
