### ISSUE TITLE
Bot sporadically disconnects from voice channels

### ISSUE THREAD

**Issue by moondownr** [owlbear-rodeo/kenku-fm#36] opened 2022-05-10 15:23 UTC
Sound output in the voice channel tends to cut off, with the bot staying visibly connected to the channel on Discord for a short period of time, then disconnecting.

Immediately reconnecting and/or quickly switching voice channels sometimes doesn't work either - the bot itself connects fine, but no sound is being transmitted. Usually, after 2-3 jumps, the music "catches up". Meanwhile, various errors are being displayed:

- connection timeout
- WebSocket was closed before the connection was established
- Unexpected server response: 525

This behaviour seems random and tends to go away after continuously using Kenku for about 20 minutes. I.e., I tend to get a bunch of these issues early while I'm setting up for the game, and than the whole 3 hour session goes without a single disconnect.

**To Reproduce**
1. Start Kenku.fm and connect to the Discord bot
2. Select a voice channel as an output
3. Start playing sounds
4. In a few minutes, sound cuts off and the bot disconnects either immediately, or after a short delay

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.1.0

**Additional context**
Please see [this discord.js bug report](https://github.com/discordjs/discord.js/issues/4302
), as it pretty much describes the same problem, as far as I can tell:

**Comment by rafaspadilha** [comment] 2022-05-20 13:00
A similar thing happens to me (OSX), but to a lesser degree. Sometimes the bot just disconnects from the channel. Clicking on the Kenku client to connect to a chat usually solves the issue.

**Comment by mitchemmc** [comment] 2022-05-21 08:57
Thanks for the report.
I haven't been able to reproduce this on any of my machines so it will take a while to do a proper investigation. I will be pretty busy over the next 2 months on Owlbear Rodeo 2.0 so I most likely won't get to investigate until then.
I will keep this thread updated though if/when I get time.

**Comment by rnicks** [comment] 2022-05-26 02:41
I'm experiencing a similar issue on Catalina (2012 MBP) - the bot connects and plays audio just fine for maybe 10-15 minutes, then audio stops although the bot is still connected to the voice channel. If I switch KenkuFM output to local computer, audio continues to play uninterrupted, but I have to close KenkuFM and re-open it to get it to start sending audio to Discord again. This happens consistently every 10-15 minutes or so. I'll do some more testing over the next few days and try to add some more details if possible. It's possible my old Macbook just can't keep up; I was also getting some intermittent audio stuttering that I was able to resolve by closing some other applications but the main issue continues.

In case anyone is interested, as a workaround for now I'm planning to use KenkuFM outputting from the headphone output of my laptop, running into the line in of another computer hosting DiscordAudioPipe to send the Kenku audio to Discord. I'd previously been using a similar setup to route audio from QLab and it worked great, but the Kenku workflow with Stream Deck streamlines things a lot compared to QLab.

**Comment by jbhaywood** [comment] 2022-06-30 01:25
I've pretty much stopped using Kenku because it just quits playing in Discord after a while. If there's a way to get debug information to you, I'm happy to help. I'd really like to use it during my game sessions.

**Comment by r-valyar** [comment] 2022-07-14 18:20
It happens once or twice per session every few sessions. It is not clear what is going on, I just have to re-join the channel.  Running on Windows 10.

**Comment by Tim98345** [comment] 2022-09-13 09:34
Hello, I've got this same issue - its happening to me on two different computers. Unfortunate, for me this is the only thing holding this great piece of software back !

**Comment by mitchemmc** [comment] 2022-11-23 05:51
We've changed the internal discord library we use in v1.2.0 which should better handle reconnecting.

I'll close this for now but if it still happens with this new library comment here and I'll look more into the issue.

**Closed by mitchemmc** 2022-11-23 05:51 UTC
Labels: bug

**Comment by Tim98345** [comment] 2022-12-06 09:02
I ran a game without issues. Thanks so much for addressing this !
